# Generated by Django 3.1.7 on 2021-03-26 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='person',
        ),
        migrations.CreateModel(
            name='MembersGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(default='My duty', max_length=50, unique=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.ForeignKey(default='New member', on_delete=django.db.models.deletion.CASCADE, to='tasks.membersgroup', to_field='member'),
            preserve_default=False,
        ),
    ]
